import assert from 'node:assert/strict';
import {esc, dateKey} from '../frontend/js/ui.js';
import {dashboard,calendar,filteredTasks,taskTable,shell} from '../frontend/js/views.js';
import {tasksCsv} from '../frontend/js/export.js';
assert.equal(esc('<img src=x onerror="bad">'), '&lt;img src=x onerror=&quot;bad&quot;&gt;');
assert.equal(dateKey(new Date(2026,0,2)), '2026-01-02');
const state={user:{display_name:'测试',role_label:'管理员'},route:'dashboard',tasks:[],people:[],month:new Date(2026,8,1),selectedDate:'2026-09-06',dashTab:'today',filter:{search:'',status:'',district:'',period:''}};
assert.ok(dashboard(state).includes('暂无符合条件的任务'));
assert.equal((calendar(state,true).match(/class="day-cell/g)||[]).length,42);
state.tasks=[{id:1,pid:'A',task_name:'<script>bad</script>',status:'pending',district:'合肥市',company:'企业'}, {id:2,pid:'B',status:'done',company:'其他'}];
assert.ok(!taskTable(state.tasks).includes('<script>'));
state.filter.status='pending';assert.equal(filteredTasks(state).length,1);
state.filter.search='其他';assert.equal(filteredTasks(state).length,0);
assert.ok(!shell(state,()=>false).includes('href="#users"'));
const csv=tasksCsv([{pid:'=1+1',task_name:'\t=SUM(1,2)',company:'含"引号,及\n换行',status:'done'}]);
assert.ok(csv.startsWith('\ufeff'));
assert.ok(csv.includes('"\'=1+1"'));
assert.ok(csv.includes('"\'\t=SUM(1,2)"'));
assert.ok(csv.includes('"含""引号,及\n换行"'));
state.tasks=[{id:1,status:'cancelled',date_start:'2026-09-06',date_end:'2026-09-07'}];
assert.ok(dashboard(state).includes('今天 · 0 项采样安排') || dashboard(state).includes('2026-09-06 · 0 项采样安排'));
console.log('UI tests: 12 assertions passed');
