import {api} from './api.js';
import {esc,icon,modal,field,select,badge,toast,labels} from './ui.js';
import {regions} from './regions.js';
import {tasksCsv} from './export.js';
export function createActions(state,can,refresh){
 const actions={};
 const after=async message=>{await refresh();toast(message);};
 actions['new-task']=()=>actions.task();
 actions['new-person']=()=>actions.person();
 actions['new-user']=()=>actions.user();
 actions.task=(id)=>{
  const t=state.tasks.find(x=>x.id===id)||{};
  const city=Object.keys(regions).find(c=>(t.district||'').startsWith(c))||'';
  modal(id?'编辑监测任务':'新建监测任务',`<div class="form-grid"><div class="form-section"><h3>基本信息</h3><p>标有 * 的项目为必填，其余信息可稍后补充。</p></div>${field('pid','任务编号 *',t.pid||'XY-'+new Date().getFullYear()+'-'+Date.now().toString().slice(-6),'text','required maxlength="50"')}${field('task_name','任务名称 *',t.task_name,'text','required maxlength="200"')}${field('company','委托企业',t.company)}${select('project_type','项目类别',['自行检测','委托检测','比对监测','验收检测'],t.project_type||'委托检测')}${select('valid_period','有效期',['月度','季度','半年度','年度','月度+季度','月度+半年度','季度+半年度','月度+季度+半年度'],t.valid_period||'月度')}${field('planned_hrs','计划工时',t.planned_hrs??0,'number','min="0" step="0.5"')}<div class="form-section"><h3>采样地点与联系信息</h3></div>${select('city','所在城市',[['','请选择城市'],...Object.keys(regions)],city)}${select('county','所在区县',[['','请选择区县'],...(regions[city]||[])],(t.district||'').replace(city,'').trim())}${field('contact_person','项目联系人',t.contact_person)}${field('contact_phone','联系电话',t.contact_phone,'tel')}${field('project_region','项目地区 / 详细地址',t.project_region)}${field('market_manager','市场经理',t.market_manager)}<div class="form-section"><h3>检测内容</h3><p>按类别填写检测项目，便于现场采样时核对。</p></div><label class="field full">检测项目（每行：类别: 项目1, 项目2）<textarea name="testing_items" placeholder="废(雨)水: pH, 氨氮\n噪声: 厂界噪声">${esc((t.testing_items||[]).map(x=>x.category+': '+x.items.join(', ')).join('\n'))}</textarea></label><label class="field full">任务备注<textarea name="note">${esc(t.note)}</textarea></label></div>`,async fd=>{
   const data=Object.fromEntries(fd);data.planned_hrs=Number(data.planned_hrs);data.district=[data.city,data.county].filter(Boolean).join(' ');delete data.city;delete data.county;
   data.testing_items=data.testing_items.split('\n').filter(x=>x.trim()).map(line=>{const parts=line.split(/[:：]/);if(parts.length<2)throw new Error('检测项目请按「类别: 项目1, 项目2」填写');return {category:parts[0].trim(),items:parts.slice(1).join(':').split(/[,，、]/).map(x=>x.trim()).filter(Boolean)};});
   await api('/tasks'+(id?'/'+id:''),id?'PUT':'POST',data);await after(id?'任务已更新':'任务已创建，可继续安排派单');
  });
  document.querySelector('[name=city]').onchange=e=>{document.querySelector('[name=county]').innerHTML='<option value="">请选择区县</option>'+(regions[e.target.value]||[]).map(d=>`<option>${esc(d)}</option>`).join('');};
 };
 actions.dispatch=id=>{
  const t=state.tasks.find(x=>x.id===id),people=state.people.filter(p=>p.status==='active');
  modal('安排采样 · '+t.task_name,`<div class="form-grid">${field('date_start','采样开始日期 *',t.date_start,'date','required')}${field('date_end','采样结束日期 *',t.date_end,'date','required')}<div class="full field">采样组长 *<div class="checkboxes">${people.filter(p=>['采样组长','field_leader'].includes(p.role)).map(p=>`<label><input name="leader_ids" type="checkbox" value="${p.id}" ${(t.leader_ids||'').split(',').includes(String(p.id))?'checked':''}>${esc(p.name)}</label>`).join('')||'请先在人员管理中添加采样组长。'}</div></div><div class="full field">采样组员<div class="checkboxes">${people.filter(p=>!['采样组长','field_leader'].includes(p.role)).map(p=>`<label><input name="member_ids" type="checkbox" value="${p.id}" ${(t.member_ids||'').split(',').includes(String(p.id))?'checked':''}>${esc(p.name)}</label>`).join('')||'暂无可选组员'}</div></div><p class="notice full">保存后任务将进入「进行中」，并显示在派单日历中。系统会检查人员在所选日期内的安排冲突。</p></div>`,async fd=>{await api('/tasks/'+id,'PUT',{date_start:fd.get('date_start'),date_end:fd.get('date_end'),leader_ids:fd.getAll('leader_ids').join(','),member_ids:fd.getAll('member_ids').join(','),status:'progress',cancel_reason:null});await after('派单已保存');});
 };
 actions.detail=async id=>{
  const t=state.tasks.find(x=>x.id===id);if(!t)return;
  const person=state.people.find(p=>p.user_id===state.user.id), leader=person&&(t.leader_ids||'').split(',').includes(String(person.id));
  const assigned=person&&[...(t.leader_ids||'').split(','),...(t.member_ids||'').split(',')].includes(String(person.id));
  const records=await api('/sampling?task_id='+id);
  const pairs=[['任务编号',t.pid],['委托企业',t.company],['项目类别',t.project_type],['有效期',t.valid_period],['采样地区',t.district],['采样日期',t.date_start?`${t.date_start} 至 ${t.date_end}`:'尚未安排'],['采样组长',t.leader_names],['采样组员',t.member_names],['联系人',`${t.contact_person||'—'} ${t.contact_phone||''}`],['计划 / 实际工时',`${t.planned_hrs} / ${t.actual_hrs??'—'} 小时`],['详细地址',t.project_region],['市场经理',t.market_manager],['检测项目',(t.testing_items||[]).map(x=>x.category+'：'+x.items.join('、')).join('\n')],['备注',t.note],...(t.cancel_reason?[['取消 / 异常原因',t.cancel_reason]]:[])];
  modal('任务详情',`<div class="detail-title"><h3>${esc(t.task_name||t.pid)}</h3>${badge(t.status)}</div><dl class="detail-grid">${pairs.map(([l,v])=>`<div><dt>${l}</dt><dd>${esc(v||'—')}</dd></div>`).join('')}</dl><h3 style="font-size:13px">采样记录 · ${records.length}</h3>${records.map(r=>`<p class="notice" style="margin:10px 0">${esc(r.date)} · ${esc(r.sampler_name)}<br>${r.ports.map(p=>esc(p.name)+'：'+esc(p.note)).join('<br>')}</p>`).join('')||'<p class="notice" style="margin:10px 0">暂无采样记录</p>'}<div class="detail-actions">${can('manage_tasks')?'<button type="button" class="button" id="edit-task">编辑任务</button><button type="button" class="button primary" id="dispatch-task">安排 / 改派</button>':''}${can('do_sampling')&&(can('manage_tasks')||assigned)?'<button type="button" class="button" id="sample-task">录入采样</button>':''}${can('manage_tasks')||leader?'<button type="button" class="button" id="finish-task">更新结果</button>':''}${can('manage_tasks')?'<button type="button" class="button danger" id="delete-task">删除</button>':''}</div>`);
  for(const [key,fn] of [['edit-task',()=>actions.task(id)],['dispatch-task',()=>actions.dispatch(id)],['sample-task',()=>actions.sample(id)],['finish-task',()=>actions.result(id)],['delete-task',()=>actions.remove('tasks',id)]]){const b=document.getElementById(key);if(b)b.onclick=fn;}
 };
 actions.result=id=>{const t=state.tasks.find(x=>x.id===id);modal('更新采样结果',`<div class="form-grid">${select('status','任务结果',[['done','已完成'],['abnormal','异常'],['cancelled','已取消']],t.status)}${field('actual_hrs','实际工时',t.actual_hrs??0,'number','min="0" step="0.5"')}<label class="field full">原因说明（异常 / 取消时必填）<textarea name="cancel_reason">${esc(t.cancel_reason)}</textarea></label></div>`,async fd=>{const data=Object.fromEntries(fd);data.actual_hrs=Number(data.actual_hrs);await api('/tasks/'+id,'PUT',data);await after('任务结果已更新');});};
 actions.sample=id=>modal('录入现场采样',`<div class="form-grid">${field('date','采样日期',new Date().toLocaleDateString('sv-SE'),'date','required')}${field('name','采样点位','','text','required')}<label class="field full">现场记录<textarea name="note" required placeholder="记录采样情况、现场条件及注意事项"></textarea></label></div>`,async fd=>{await api('/sampling','POST',{task_id:id,date:fd.get('date'),ports:[{name:fd.get('name'),note:fd.get('note'),photoCount:0,photoNames:[]}]});await after('采样记录已保存');});
 actions.person=id=>{const p=state.people.find(x=>x.id===id)||{};modal(id?'编辑人员':'添加人员',`<div class="form-grid">${field('name','姓名 *',p.name,'text','required')}${field('phone','联系电话',p.phone,'tel')}${select('role','角色',['采样组长','采样组员'],p.role==='field_leader'?'采样组长':p.role==='field_member'?'采样组员':p.role||'采样组员')}${select('leader_id','所属组长',[['','无'],...state.people.filter(x=>x.id!==id&&['采样组长','field_leader'].includes(x.role)).map(x=>[x.id,x.name])],p.leader_id||'')}${id?select('status','状态',[['active','在职'],['inactive','停用']],p.status):''}</div>`,async fd=>{const data=Object.fromEntries(fd);data.leader_id=data.leader_id?Number(data.leader_id):null;await api('/personnel'+(id?'/'+id:''),id?'PUT':'POST',data);await after('人员资料已保存');});};
 actions.invite=async id=>{const p=state.people.find(x=>x.id===id);const url=location.origin+'/register?code='+encodeURIComponent(p.reg_code);modal('邀请 '+p.name+' 加入',`<p class="notice">将以下链接提供给这位成员，完成注册后自动关联人员资料。</p><div style="margin:20px 0">${field('invite','注册链接',url,'text','readonly')}</div><div class="actions"><button type="button" class="button primary" id="copy-invite">复制链接</button><button type="button" class="button" id="reset-invite">重置注册码</button></div>`);document.getElementById('copy-invite').onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('注册链接已复制');}catch{document.querySelector('[name=invite]').select();toast('请复制选中的链接');}};document.getElementById('reset-invite').onclick=async()=>{try{await api('/personnel/'+id+'/regenerate-code','POST');await refresh();await actions.invite(id);}catch(e){toast(e.message);}};};
 actions.user=id=>{const u=state.users.find(x=>x.id===id)||{};const role=u.role||'field_member', perms=u.permissions||state.meta.templates[role]||{};modal(id?'编辑账号与权限':'创建用户',`<div class="form-grid">${!id?field('username','用户名 *','','text','required minlength="2"'):''}${field('display_name','显示名称 *',u.display_name,'text','required')}${field('password',id?'新密码（留空不修改）':'密码 *','','password',id?'minlength="8"':'required minlength="8"')}${select('role','角色模板',state.meta.roles.filter(r=>state.user.role==='admin'||r.key!=='admin').map(r=>[r.key,r.label]),role)}${field('phone','联系电话',u.phone,'tel')}${id?select('status','账号状态',[['active','正常'],['inactive','停用']],u.status):''}<div class="field full">访问权限<div class="checkboxes">${state.meta.permissions.map(p=>`<label><input type="checkbox" name="perm" value="${p.key}" ${perms[p.key]?'checked':''}>${esc(p.label)}</label>`).join('')}</div></div></div>`,async fd=>{const data=Object.fromEntries(fd);delete data.perm;data.permissions=Object.fromEntries(state.meta.permissions.map(p=>[p.key,fd.getAll('perm').includes(p.key)]));if(id&&!data.password)delete data.password;await api('/users'+(id?'/'+id:''),id?'PUT':'POST',data);state.user=await api('/auth/me');await after('用户权限已保存');});document.querySelector('[name=role]').onchange=e=>{const template=state.meta.templates[e.target.value]||{};document.querySelectorAll('[name=perm]').forEach(input=>input.checked=!!template[input.value]);};};
 actions.remove=(kind,id)=>modal('确认删除',`<p class="notice">删除后无法恢复。关联任务或采样记录的数据需要先处理其关联关系。</p>`,async()=>{await api('/'+kind+'/'+id,'DELETE');await after('已删除');},'确认删除');
 actions.password=()=>modal('修改登录密码',`<div class="form-grid">${field('current_password','当前密码','','password','required')}${field('new_password','新密码（至少 8 位）','','password','required minlength="8"')}</div>`,async fd=>{await api('/auth/password','POST',Object.fromEntries(fd));toast('密码已修改');});
 actions.exportTasks=tasks=>{const url=URL.createObjectURL(new Blob([tasksCsv(tasks)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='星源监测任务.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('已生成 '+tasks.length+' 项任务的 CSV，下载由浏览器处理');};
 return actions;
}


