import {esc,icon,badge,empty,dateKey,labels} from './ui.js';
export const landscape = '<div class="landscape" aria-hidden="true"><div class="sun"></div><div class="hill two"></div><div class="hill"></div><div class="tree"></div><div class="tree two"></div></div>';
export const brand = `<div class="brand"><div class="brand-mark">${icon('leaf',26)}</div><div><b>星源</b><small>XINGYUAN</small></div></div>`;
export const routeMeta = {dashboard:['工作台','WORKSPACE','查看任务进度，安排今天的采样工作。'],tasks:['任务管理','TASK MANAGEMENT','从任务录入到采样完成，全流程清晰可见。'],dispatch:['派单计划','DISPATCH CALENDAR','合理安排每一天，让团队高效协作。'],personnel:['人员管理','TEAM MEMBERS','连接每一位成员，汇聚专业力量。'],users:['用户管理','ACCESS MANAGEMENT','统一管理账号、角色与访问权限。']};
export function shell(state, can) {
 const route=state.route, meta=routeMeta[route];
 const nav=[['dashboard','grid'],['tasks','tasks'],['dispatch','calendar'],['personnel','people'],['users','shield']].filter(([r])=>r!=='users'||can('manage_users')).filter(([r])=>r!=='dispatch'||can('view_dispatch'));
 return `<div class="app-shell"><header class="app-header">${brand}<button class="icon-button mobile-menu" data-action="menu" aria-label="展开导航" aria-expanded="false">${icon('menu')}</button><nav class="sidebar" aria-label="主导航"><button class="icon-button nav-close" data-action="menu" aria-label="收起导航">${icon('close')}</button>${nav.map(([r,i])=>`<a class="nav-link ${r===route?'active':''}" href="#${r}" ${r===route?'aria-current="page"':''}>${icon(i,18)}<span>${routeMeta[r][0]}</span></a>`).join('')}</nav><button class="nav-backdrop" data-action="menu" aria-label="关闭导航遮罩"></button><div class="account-tools"><button class="icon-button" data-action="password" aria-label="修改密码">${icon('shield',18)}</button><div class="avatar">${esc(state.user.display_name[0])}</div><span class="account-name">${esc(state.user.display_name)}<small>${esc(state.user.role_label)}</small></span><button class="icon-button" data-action="logout" aria-label="退出登录">${icon('logout',18)}</button></div></header><main class="workspace"><div class="page-heading"><div><div class="page-context">星源环境监测 / ${meta[0]}</div><h1>${meta[0]}</h1><p class="subtitle">${meta[2]}</p></div><div class="actions">${['dashboard','tasks'].includes(route)?`<button class="button" data-action="export">${icon('download',16)}导出任务</button>`:''}${can(route==='personnel'?'manage_personnel':route==='users'?'manage_users':'manage_tasks')?`<button class="button primary" data-action="${route==='personnel'?'new-person':route==='users'?'new-user':'new-task'}">${icon('plus',18)}${route==='personnel'?'添加人员':route==='users'?'新建用户':'新建任务'}</button>`:''}</div></div><div id="page"></div><footer class="footer-note"><span>星源环境监测协作平台</span><span>${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'})}</span></footer></main></div>`;
}
export function taskTable(tasks, compact=false) {
 if(!tasks.length) return empty('暂无符合条件的任务','新建监测任务，或调整筛选条件后查看。');
 return `<div class="queue ${compact?'queue-compact':''}"><div class="queue-heading"><span>监测项目</span><span>采样安排</span><span>任务状态</span></div>${tasks.map(t=>`<button class="queue-row" data-task="${t.id}"><span class="queue-project"><span class="project-symbol">${icon('tasks',20)}</span><span><strong>${esc(t.task_name||t.company||t.pid)}</strong><small>${esc(t.pid)} · ${esc(t.company||t.project_type||'待补充企业')}</small></span></span><span class="queue-schedule"><strong>${esc(t.district||'地区待填写')}</strong><small>${t.date_start?esc(t.date_start)+' 至 '+esc(t.date_end||t.date_start):'采样日期待安排'}<br>${esc(t.leader_names||'负责人待分配')}</small></span><span class="queue-status">${badge(t.status)}${icon('chevron',15)}</span></button>`).join('')}</div>`;
}
export function calendar(state, large=false) {
 const month=state.month, year=month.getFullYear(), m=month.getMonth();
 const first=new Date(year,m,1), start=new Date(year,m,1-(first.getDay()+6)%7);
 const days=Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i));
 const header=`<div class="panel-header"><h2>${year} 年 ${m+1} 月</h2><div class="actions"><button class="icon-button" data-month="-1" aria-label="上个月">‹</button><button class="text-button" data-month="0">今天</button><button class="icon-button" data-month="1" aria-label="下个月">›</button></div></div>`;
 const weekdays=`<div class="calendar-week">${['一','二','三','四','五','六','日'].map(d=>`<span>${d}</span>`).join('')}</div>`;
 return `<section class="panel">${header}${large?'<div class="calendar-scroller">':'<div class="mini-calendar">'}${weekdays}<div class="${large?'calendar-large':'mini-days'}">${days.map(d=>{const key=dateKey(d), tasks=state.tasks.filter(t=>t.date_start&&t.date_start<=key&&t.date_end>=key&&t.status!=='cancelled');return large?`<div class="day-cell ${d.getMonth()!==m?'muted':''} ${key===dateKey(new Date())?'is-today':''}"><span class="day-number">${d.getDate()}</span>${tasks.map(t=>`<button class="calendar-task ${t.status}" data-task="${t.id}" title="${esc(t.task_name)}">${esc(t.task_name||t.pid)}<br>${esc(t.leader_names||'未分配')}</button>`).join('')}</div>`:`<button data-date="${key}" class="${d.getMonth()!==m?'muted':''} ${key===dateKey(new Date())?'today':''} ${key===state.selectedDate?'selected':''} ${tasks.length?'has-tasks':''}">${d.getDate()}</button>`;}).join('')}</div></div><div class="calendar-legend"><span><i class="legend-dot"></i>已安排采样</span><span>周一至周日 · 点击查看任务</span></div></section>`;
}
export function dashboard(state) {
 const counts=Object.fromEntries(Object.keys(labels).map(s=>[s,state.tasks.filter(t=>t.status===s).length]));
 const relevant=state.tasks.filter(t=>t.status!=='cancelled'&&t.date_start&&t.date_start<=state.selectedDate&&t.date_end>=state.selectedDate);
 const shown=(state.dashTab==='today'?relevant:state.dashTab==='pending'?state.tasks.filter(t=>t.status==='pending'):state.tasks.filter(t=>t.status==='abnormal')).slice(0,5);
 const today=state.selectedDate===dateKey(new Date());
 const active=state.tasks.filter(t=>t.status!=='cancelled'),percent=active.length?Math.round(counts.done/active.length*100):0;
 return `<section class="operations-intro"><div class="intro-copy"><span class="intro-date">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</span><h2>把今天的采样，<br>安排妥当。</h2><p>${esc(state.user.display_name)}，当前有 <b>${counts.pending}</b> 项任务等待派单，<b>${counts.abnormal}</b> 项异常需要关注。</p><a href="#tasks" class="intro-link">进入任务队列 ${icon('arrow',18)}</a></div><div class="ambient-surface"><canvas data-ambient aria-hidden="true"></canvas><div class="intro-summary"><span>正在执行</span><strong>${counts.progress}<small>项任务</small></strong><span>从派单到采样，跟进每一步进度。</span></div></div></section><section class="metric-bar" aria-label="任务统计">${[['全部项目',state.tasks.length,'tasks'],['待派单',counts.pending,'clock'],['已完成',counts.done,'check'],['采样完成率',percent+'%','grid']].map(([l,n,i])=>`<div><span>${icon(i,16)}${l}</span><strong>${n}</strong></div>`).join('')}</section><div class="dashboard-grid"><section class="panel task-panel"><div class="panel-header"><div><h2>采样任务队列</h2><p>${today?'今天':state.selectedDate} · ${relevant.length} 项采样安排</p></div><a class="text-button" href="#tasks">全部任务 ${icon('arrow',16)}</a></div><div class="tabs">${[['today',today?'今日采样':state.selectedDate],['pending','等待派单'],['abnormal','异常关注']].map(([v,l])=>`<button data-dash-tab="${v}" class="tab ${state.dashTab===v?'active':''}">${l}</button>`).join('')}</div>${taskTable(shown,true)}</section><aside class="dashboard-aside">${calendar(state)}<section class="team-strip"><div class="panel-header"><h2>采样团队</h2><a href="#personnel" class="text-button">管理人员</a></div>${state.people.filter(p=>['采样组长','field_leader'].includes(p.role)).slice(0,4).map(p=>`<div class="team-row"><div class="avatar">${esc(p.name[0])}</div><div><strong>${esc(p.name)}</strong><small>采样组长</small></div><span class="workload">${state.tasks.filter(t=>(t.leader_ids||'').split(',').includes(String(p.id))&&t.status==='progress').length} 项执行中</span></div>`).join('')||empty('添加你的采样团队','先建立组长和组员，再安排任务。')}</section></aside></div>`;
}
export function filteredTasks(state) {return state.tasks.filter(t=>(!state.filter.status||t.status===state.filter.status)&&(!state.filter.search||[t.pid,t.task_name,t.company].some(v=>(v||'').toLowerCase().includes(state.filter.search.toLowerCase())))&&(!state.filter.district||(t.district||'').includes(state.filter.district))&&(!state.filter.period||t.valid_period===state.filter.period));}
export function tasksView(state) {
 const tasks=filteredTasks(state), pages=Math.max(1,Math.ceil(tasks.length/10));state.page=Math.min(state.page,pages);
 return `<section class="panel"><div class="tabs">${[['','全部任务'],...Object.entries(labels)].map(([v,l])=>`<button class="tab ${state.filter.status===v?'active':''}" data-status="${v}">${l} <small>${v?state.tasks.filter(t=>t.status===v).length:state.tasks.length}</small></button>`).join('')}</div><div class="filter-bar"><label class="search">${icon('search',16)}<input id="task-search" placeholder="搜索任务名称、编号或企业…" value="${esc(state.filter.search)}" aria-label="搜索任务"></label><select id="district-filter" aria-label="地区筛选"><option value="">全部地区</option>${[...new Set(state.tasks.map(t=>t.district).filter(Boolean))].map(d=>`<option ${state.filter.district===d?'selected':''}>${esc(d)}</option>`).join('')}</select><select id="period-filter" aria-label="有效期筛选"><option value="">全部有效期</option>${['月度','季度','半年度','年度','月度+季度','月度+半年度','季度+半年度','月度+季度+半年度'].map(d=>`<option ${state.filter.period===d?'selected':''}>${d}</option>`).join('')}</select><button class="text-button" data-action="reset-filter">重置</button></div>${taskTable(tasks.slice((state.page-1)*10,state.page*10))}<div class="table-footer"><span>共 ${tasks.length} 项任务</span><div class="actions"><button class="icon-button" data-page="-1" ${state.page===1?'disabled':''} aria-label="上一页">‹</button>${state.page} / ${pages}<button class="icon-button" data-page="1" ${state.page===pages?'disabled':''} aria-label="下一页">›</button></div></div></section>`;
}
export function peopleView(state,can) {
 if(!state.people.length)return `<section class="panel">${empty('建立你的采样团队','点击「添加人员」，设置组长和组员的归属关系。')}</section>`;
 return `<section class="directory"><div class="directory-heading"><span>团队成员 / ${state.people.length}</span><span>联系与归属</span><span>账号关联</span><span>管理</span></div>${state.people.map(p=>`<article class="directory-row"><div class="member-identity"><div class="avatar">${esc(p.name[0])}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.role==='field_leader'?'采样组长':p.role==='field_member'?'采样组员':p.role)}<span class="member-state">${p.status==='active'?'在职':'已停用'}</span></p></div></div><div class="directory-info"><strong>${esc(p.phone||'电话未填写')}</strong><small>所属组长：${esc(p.leader_name||'未设置')}</small></div><div class="directory-info"><strong>${esc(p.account_username||'尚未注册')}</strong><small>${p.has_account?'已关联登录账号':'可通过邀请链接注册'}</small></div><div class="directory-actions">${can('manage_personnel')?`<button class="button" data-person="${p.id}">编辑</button>${!p.has_account?`<button class="text-button" data-invite="${p.id}">邀请注册</button>`:''}<button class="icon-button" data-delete-person="${p.id}" aria-label="删除人员 ${esc(p.name)}">${icon('close',16)}</button>`:''}</div></article>`).join('')}</section>`;
}
export function usersView(state){return `<section class="panel"><div class="panel-header"><h2>账号与权限 <small>${state.users.length}</small></h2></div><div class="table-wrap"><table><thead><tr><th>用户</th><th>用户名</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>${state.users.map(u=>`<tr><td><strong>${esc(u.display_name)}</strong></td><td>${esc(u.username)}</td><td>${esc(state.meta.roles.find(r=>r.key===u.role)?.label||u.role)}</td><td>${u.status==='active'?'正常':'已停用'}</td><td><button class="text-button" data-user="${u.id}">编辑权限</button> ${u.id!==state.user.id?`<button class="text-button" data-delete-user="${u.id}">删除</button>`:''}</td></tr>`).join('')}</tbody></table></div></section>`;}

